"""Add ESG data models

Revision ID: 366f28c6065b
Revises: 3b8ebdacab78
Create Date: 2026-01-01 22:36:47.945905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366f28c6065b'
down_revision = '3b8ebdacab78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('emission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('scope', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), nullable=False),
    sa.Column('activity_data', sa.FLOAT(), nullable=False),
    sa.Column('emission_factor', sa.FLOAT(), nullable=False),
    sa.Column('total_emission', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
